//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcomisionvendedor
    {
        public int comision { get; set; }
        public string tblusuario_nombreUsuario { get; set; }
        public int id { get; set; }
    
        public virtual tblusuario tblusuario { get; set; }
    }
}
