//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhistorialcompra
    {
        public System.DateTime fecha { get; set; }
        public int cantidad { get; set; }
        public int totalCompra { get; set; }
        public string tblproducto_producto { get; set; }
        public string tblusuario_nombreUsuario { get; set; }
        public int ID { get; set; }
    
        public virtual tblproducto tblproducto { get; set; }
        public virtual tblusuario tblusuario { get; set; }
    }
}
