//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusuario
    {
        public tblusuario()
        {
            this.tblcomisionespagadas = new HashSet<tblcomisionespagadas>();
            this.tblcomisionvendedor = new HashSet<tblcomisionvendedor>();
            this.tblhistorialcompra = new HashSet<tblhistorialcompra>();
        }
    
        public string nombreUsuario { get; set; }
        public string clave { get; set; }
        public string rolUsuario { get; set; }
    
        public virtual ICollection<tblcomisionespagadas> tblcomisionespagadas { get; set; }
        public virtual ICollection<tblcomisionvendedor> tblcomisionvendedor { get; set; }
        public virtual ICollection<tblhistorialcompra> tblhistorialcompra { get; set; }
    }
}
